"use client";

import { useEffect, useState } from "react";
import { useRequireAuth } from "@/lib/useRequireAuth";
import { api } from "@/lib/apiClient";
import type { Insight } from "@/lib/types";

export default function InsightsPage() {
  const { ready } = useRequireAuth();
  const [insights, setInsights] = useState<Insight[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (ready) {
      api.listInsights().then((data) => {
        setInsights(data);
        setLoading(false);
      });
    }
  }, [ready]);

  if (!ready) return null;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-lg font-semibold">Insights</h1>
        <p className="text-sm text-muted mt-0.5">
          Generated by the Advisor Agent - restock suggestions and other observations, created
          automatically when a sale or stock change crosses a threshold worth flagging.
        </p>
      </div>

      {loading && <p className="text-sm text-muted">Loading...</p>}

      {!loading && insights.length === 0 && (
        <div className="card text-center text-sm text-muted py-10">
          No insights yet. These appear automatically - for example, selling stock down to its
          reorder level will trigger a restock suggestion here.
        </div>
      )}

      <div className="space-y-3">
        {insights.map((insight) => (
          <div key={insight.id} className="card flex items-start justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="badge bg-accent/10 text-accent-dark">{insight.insight_type}</span>
                {insight.confidence !== null && (
                  <span className="text-xs text-muted">
                    {(insight.confidence * 100).toFixed(0)}% confidence
                  </span>
                )}
              </div>
              <p className="text-sm">{insight.message}</p>
            </div>
            <span className="text-xs text-muted shrink-0">
              {new Date(insight.created_at).toLocaleDateString()}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}
