"""add entities and final_response to voice_commands

Revision ID: 0640cc76b963
Revises: ac319f7df3e4
Create Date: 2026-07-22 08:38:20.053286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0640cc76b963'
down_revision: Union[str, Sequence[str], None] = 'ac319f7df3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_commands', sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('voice_commands', sa.Column('final_response', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_commands', 'final_response')
    op.drop_column('voice_commands', 'entities')
    # ### end Alembic commands ###
