"""fix embedding dim to 2048, add document title, make file_url nullable

Revision ID: 2782ffd2205e
Revises: 0640cc76b963
Create Date: 2026-07-28 11:42:19.104505
 
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '2782ffd2205e'
down_revision: Union[str, Sequence[str], None] = '0640cc76b963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=2048),
               existing_nullable=True)
    op.add_column('documents', sa.Column('title', sa.String(length=200), nullable=False))
    op.alter_column('documents', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('documents', 'title')
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=2048),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###
